### ISSUE TITLE
how can i become a contributor to upload tasks of the last meeting?

### ISSUE THREAD

**Issue by devCharles** [unamfi/CarTheftBot#6]
i want to add the last news in a folder called "minutas" but i tried to make a new branch but i do not have the access level to do that 
well i will just leave here the info and if someone can create a marckdown file please upload it

# (Car Theft) Minuta de reunión
Martes 2 de Agosto de 2017

Participantes, experiencia y tareas:

* Africa - Diseño de pantallas, maqueta.

* Vivi Nava - Diseño de pantallas, maqueta.  Bot.

* Josue Gutierrez - Infraestructura, Clouds.

* Julio Cesar - Github

* Julio Fruta - iOS Developer

* Sandra Barron - Project Manager, Scrum, UX

* Carlos Silva - Bots

* Roberto Gonzales - Experiencia en desarrollo de aplicaciones para Android.

* Paola - API en Python

* Daniel Arturo - Trabajo en Lo Jack, análisis de datos, inteligencia de negocios.

* Josu Sánchez - Seguridad, infraestructura en Google.

* Juan Gonzalez - Big Data.

* Miguel Salazar - Data Scientist, Director de Codeando Mexico.

* Brian - Desarrollador backend , principalmente Python y php, he trabajado con reconocimiento de voz, nlp, y como hobbie aprendiendo cosas de IA y machine learning

---

# Historias - Sprint 0

* Crear grupo en Slack - Alberto Ladron(alberto.ladron@gmail.com)
* Crear prototipo de Bot - Norma Saavedra, Carlos Silva, Vivi Nava,
* Crear Maqueta de aplicacion para reportar vehiculo robado - Africa, Sandra Barron
* Listar datos a capturar en FNOL(First Notice Of Loss) - Alberto Ladron
* Investigacion - Todo el equipo
* Creacion de tarjetas de historias en Trello - Carlos Silva
* Creacion de API en swagger - Alberto Ladron, Rogelio De La Cruz(rogelio.delacruz.basilio@gmail.com)
* Instalacion de ambiente para desarrollo con Xamarin - David Morales
* Crear Maqueta de aplicación en Xamarin para reportar vehiculo robado - David Morales
* Crear encuesta para decidir horario de próximas reuniones - Norma Saavedra
* AWS - Evaluacion de arquitecturas en la nube - Andy Barr andybar@gmail.com
* Azure - Evaluación de arquitecturas en la nube - Josuesgutierrez ; gutierrezjosue@comunidad.unam.mx
* Administracion de proyecto en GIT - Julio Cesar

**Comment by juliofruta** [comment]
Hola Carlos. Te mandé el invite. https://github.com/unamfi/CarTheftBot/invitations
